In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("D:\downloads\Assignment data -2023.csv")
df

,Districts,STATES,Forest cover,Yield variability,Female literacy rate,Slope >30 degree,Population Density,% BPL Households,Infant Mortality Rate,MGNREGA
0,Anjaw,Arunachal Pradesh,66.66,0.14,43.17,89.18,3.0,63.00,102.00,27.38
1,KULGAM,J&K,35.17,0.64,51.51,0.13,1035.0,25.37,23.00,34.00
2,Kurung Kumey,Arunachal Pradesh,87.79,0.12,42.64,84.39,15.0,71.00,108.00,17.51
3,Upper Subansiri,Arunachal Pradesh,79.22,0.21,57.59,83.50,12.0,65.00,90.00,29.15
4,Tawang,Arunachal Pradesh,54.19,0.06,46.23,80.63,23.0,64.00,67.00,29.30
...,...,...,...,...,...,...,...,...,...,...
131,Wokha,Nagaland,80.22,0.14,74.35,36.52,102.0,13.10,10.67,55.96
132,Tamenglong,Manipur,90.03,0.20,63.69,12.39,32.0,8.01,42.00,25.60
133,Peren,Nagaland,87.10,0.14,60.80,30.91,58.0,13.18,10.67,54.20
134,Ukhrul,Manipur,81.56,0.14,76.95,5.28,40.0,7.75,49.00,31.66
135,Churachandpur,Manipur,91.23,0.18,78.57,5.89,60.0,8.43,43.00,42.35

In [4]:
df.describe()

,Forest cover,Yield variability,Female literacy rate,Slope >30 degree,Population Density,% BPL Households,Infant Mortality Rate,MGNREGA
count,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000
mean,51.283088,0.184779,63.813897,23.478897,281.750147,30.686618,40.627353,41.629191
std,26.997620,0.134495,12.618247,28.962657,285.099185,20.462242,24.866035,21.559616
min,0.210000,0.000000,22.870000,0.000000,1.000000,0.850000,1.180000,8.360000
25%,28.900000,0.090000,57.062500,0.285000,56.250000,12.252500,19.855000,25.187500
50%,53.460000,0.140000,64.445000,7.070000,185.280000,26.980000,42.000000,36.045000
75%,76.507500,0.222500,72.297500,46.140000,410.000000,42.625000,58.000000,58.155000
max,92.170000,0.640000,89.700000,90.450000,1313.000000,71.000000,111.000000,98.560000

In [6]:
df.corr()

,Forest cover,Yield variability,Female literacy rate,Slope >30 degree,Population Density,% BPL Households,Infant Mortality Rate,MGNREGA
Forest cover,1.000000,-0.134579,0.147087,0.575850,-0.587809,0.244880,0.033953,0.169711
Yield variability,-0.134579,1.000000,-0.250522,-0.090560,0.246668,-0.200473,-0.217160,-0.078988
Female literacy rate,0.147087,-0.250522,1.000000,-0.073014,0.073589,0.032576,0.026215,0.249888
Slope >30 degree,0.575850,-0.090560,-0.073014,1.000000,-0.565344,0.163148,0.086189,0.039232
Population Density,-0.587809,0.246668,0.073589,-0.565344,1.000000,-0.133017,-0.027818,-0.200212
% BPL Households,0.244880,-0.200473,0.032576,0.163148,-0.133017,1.000000,0.422283,-0.048886
Infant Mortality Rate,0.033953,-0.217160,0.026215,0.086189,-0.027818,0.422283,1.000000,-0.355977
MGNREGA,0.169711,-0.078988,0.249888,0.039232,-0.200212,-0.048886,-0.355977,1.000000